"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.1.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from datetime import timedelta

import environ

# ساخت متغیر BASE_DIR (مسیر اصلی پروژه)
BASE_DIR = Path(__file__).resolve().parent.parent

# ساخت شیء env
env = environ.Env()

# خواندن فایل .env از مسیر اصلی پروژه
environ.Env.read_env(BASE_DIR / ".env")

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-%zlh3($#3z+-81z&rd3$z)m^celcmz-#0i5yr00f-!qz64q#o4"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    
    # apps
    "accounts.apps.AccountsConfig",
    
    # third party
    "rest_framework",
    "django_jalali",
    "django_filters",
    "drf_spectacular",
    "rest_framework_simplejwt",
    "corsheaders",
    "silk",
    # توجه: rest_framework_simplejwt.token_blacklist عمداً نصب نیست — این اپ
    # متن کامل هر refresh token صادرشده رو در OutstandingToken و هر توکن
    # باطل‌شده رو در BlacklistedToken، در دیتابیس ذخیره می‌کرد. به‌جاش
    # logout/تغییر رمز کاملاً stateless پیاده شده (کش برای logout تک‌نشست،
    # امضای وابسته به رمز عبور برای ابطال همه‌ی نشست‌ها) —
    # accounts/services/tokens.py و accounts/api/v1/authentication.py را ببینید.
]

MIDDLEWARE = [
    "silk.middleware.SilkyMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "academi_v2_mahsa_db",
        "USER": "postgres",
        "PASSWORD": "YaZahra_110",
        "HOST": "185.147.161.216",
        "PORT": "5432",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

STATIC_URL = "static/"

AUTH_USER_MODEL = 'accounts.User'

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'fa'

# تنظیم منطقه زمانی ایران (اختیاری اما توصیه شده)
TIME_ZONE = 'Asia/Tehran'

USE_I18N = True

USE_TZ = True

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

if DEBUG:
    # حالت توسعه: اگه روی سیستم‌تون Redis نصب/بالا نیست (یا نمی‌خواید نصبش
    # کنید)، همین کش حافظه‌ای (in-memory) کافیه تا runserver بدون خطا بالا
    # بیاد و بتونید ثبت‌نام/OTP/ورود رو تست کنید. محدودیتش اینه که با هر ری‌استارت
    # سرور (یا هر پردازش/worker جدا) پاک می‌شه و بین چند process مشترک نیست —
    # برای تست دستی روی یک runserver مشکلی نداره.
    CACHES = {"default": {"BACKEND": "django.core.cache.backends.locmem.LocMemCache"}}
else:
    # حالت production: حتماً باید همین Redis واقعی باشه — چون rate-limit
    # ثبت‌نام/OTP (accounts/services/otp.py) به رفتار اتمیک و مشترک بین
    # چند process نیاز داره که فقط Redis واقعی تضمینش می‌کنه.
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": env("REDIS_URL", default="redis://localhost:6379/2"),
            "KEY_PREFIX": "rasekhoon_academy",
            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient",
            },
            "TIMEOUT": None,  # پیش‌فرض کش رو بی‌نهایت نذار؛ هر cache.set خودش timeout مشخص می‌کنه
        }
    }


REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        # به‌جای JWTAuthentication خام simplejwt: همون رفتار + رد کردن
        # access tokenی که رمز عبور صاحبش بعد از صدورش عوض شده
        # (accounts/api/v1/authentication.py).
        "accounts.api.v1.authentication.AppJWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
    # جلوگیری از brute-force و اسکن API — پیش‌فرض کلی، هر ویو می‌تونه override کنه
    "DEFAULT_THROTTLE_CLASSES": (
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ),
    "DEFAULT_THROTTLE_RATES": {
        "anon": "20/minute",
        "user": "120/minute",
        # مسیرهای حساس فراموشی/تغییر رمز عبور: هم جلوی اسپم پیامک OTP رو
        # می‌گیره هم جلوی brute-force حدس زدن رمز فعلی در تغییر رمز.
        # ScopedRateThrottle به‌صورت خودکار برای کاربر لاگین‌شده بر اساس
        # شناسه‌ی کاربر و برای کاربر مهمان بر اساس IP شمارش می‌کنه.
        "password_security": "10/hour",
    },
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_FILTER_BACKENDS": (
        "django_filters.rest_framework.DjangoFilterBackend",
    ),
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 12,
}


SIMPLE_JWT = {
    # عمر کوتاه access token — حتی اگه دزدیده بشه، زود از کار می‌افته
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=5),
 
    # عمر بلند refresh token — تا وقتی کاربر با همین دستگاه فعاله، لاگینش می‌مونه
    "REFRESH_TOKEN_LIFETIME": timedelta(days=365),
 
    # هر بار access token رو با refresh token تمدید می‌کنی، یه refresh token
    # *جدید* هم صادر می‌شه و قدیمی باطل می‌شه — یعنی عملاً "sliding session":
    # تا وقتی کاربر حداقل هر ۳۶۵ روز یک‌بار اپ رو باز کنه، هیچ‌وقت لاگ‌اوت نمی‌شه.
    "ROTATE_REFRESH_TOKENS": True,
    # قبلاً True بود و به token_blacklist وابسته بود (خودِ توکن قدیمی رو
    # بعد از هر رفرش در دیتابیس باطل می‌کرد). چون اون اپ دیگه نصب نیست،
    # این تنظیم رو صادقانه False گذاشتیم؛ True نگه داشتنش صرفاً نادیده
    # گرفته می‌شد (simplejwt خودش AttributeError رو silent catch می‌کنه)
    # و گمراه‌کننده بود. توکن قدیم بعد از rotation طبیعتاً بی‌استفاده
    # می‌مونه ولی تا انقضای طبیعی‌اش معتبره — دقیقاً مثل هر access token
    # دیگه‌ای که هیچ‌وقت صریحاً logout نشده.
    "BLACKLIST_AFTER_ROTATION": False,

    "UPDATE_LAST_LOGIN": True,
 
    "ALGORITHM": "HS256",
    "SIGNING_KEY": env("JWT_SIGNING_KEY", default=SECRET_KEY),
    "AUTH_HEADER_TYPES": ("Bearer",),
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
 
    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
}

# عمر توکن یک‌بارمصرفِ بازیابی رمز عبور — یک نوع JWT کاملاً جدا از
# access/refresh (accounts/services/tokens.py::PasswordResetToken)، فقط
# برای رد شدن از «تایید کد پیامکی» به «ثبت رمز جدید». کوتاه نگه داشته شده
# چون این توکن هیچ دسترسی دیگه‌ای به حساب نمی‌ده و AUTH_TOKEN_CLASSES بالا
# هم به AccessToken محدوده، پس حتی اگه این توکن به‌جای Bearer token فرستاده
# بشه، JWTAuthentication به خاطر ناهم‌خوانی token_type ردش می‌کنه.
PASSWORD_RESET_TOKEN_LIFETIME = timedelta(minutes=10)

# تنظیمات کوکی httpOnly که refresh token در آن نگه داشته می‌شود
# (accounts/api/v1/cookies.py). access token هرگز کوکی نمی‌شود؛ فقط در
# پاسخ JSON برمی‌گردد تا فرانت آن را در حافظه‌ی موقت نگه دارد.
#
# SECURE=True یعنی این کوکی فقط روی HTTPS فرستاده می‌شود — در DEBUG (توسعه‌ی
# محلی روی http://) False است تا در محیط توسعه هم قابل تست باشد.
REFRESH_TOKEN_COOKIE_SECURE = not DEBUG
# "Lax" برای فرانت هم-origin (یا پشت reverse proxy مشترک) کافی و امن‌تر از
# "None" است. اگر فرانت روی دامنه‌ی کاملاً جدا اجرا شود (cross-site)، باید
# این مقدار به "None" تغییر کند و هم‌زمان CORS (با CORS_ALLOW_CREDENTIALS=True
# و یک origin مشخص، نه "*") پیکربندی شود — نگاه کنید به توضیح کامل در
# accounts/api/v1/cookies.py.
REFRESH_TOKEN_COOKIE_SAMESITE = "Lax"


SPECTACULAR_SETTINGS = {
    "TITLE": "Smart Learning Dashboard API",
    "DESCRIPTION": "مستندات API داشبورد آکادمی راسخون",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
}


SMS_PROVIDER_CLASS = "accounts.services.sms.sms_ir.SmsIrProvider"
SMS_IR_API_KEY = env("SMS_IR_API_KEY")
SMS_IR_OTP_TEMPLATE_ID = env("SMS_IR_OTP_TEMPLATE_ID")

# Client ID اپلیکیشن گوگل (از Google Cloud Console) — همون Client ID که فرانت
# (وب/موبایل) موقع Sign in with Google استفاده می‌کنه. accounts.services.google_auth
# با همین مقدار claim «aud» توکن دریافتی رو چک می‌کنه.
# default="" عمداست: تا وقتی این مقدار رو در .env نذاشتید، بقیه‌ی سرور
# (ثبت‌نام/OTP/ورود معمولی) بدون مشکل بالا میاد؛ فقط اندپوینت ورود با گوگل
# در این حالت همیشه با خطای «توکن نامعتبر» رد می‌شه، نه اینکه کل سرور کرش کنه.
GOOGLE_OAUTH_CLIENT_ID = env("GOOGLE_OAUTH_CLIENT_ID", default="")


# لاگ‌گیری از رویدادهای امنیتی حساب کاربری (ورود موفق/ناموفق، verify-otp) —
# accounts/api/v1/serializers.py و views.py با logging.getLogger(__name__)
# لاگ می‌کنن. بدون این تنظیم، پیام‌های سطح INFO توسط پیکربندی پیش‌فرض جنگو
# نمایش داده نمی‌شن (فقط WARNING به بالا از طریق هندلر پیش‌فرض دیده می‌شه).
# disable_existing_loggers=False عمداً False است تا لاگرهای پیش‌فرض جنگو
# (django.request برای خطاهای ۵۰۰ و ...) دست‌نخورده بمونن.
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "[{asctime}] {levelname} {name}: {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "loggers": {
        "accounts": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}

